/**
 * Sign and send unsigned transactions generated by byreal-cli.
 *
 * Usage (pipe from CLI):
 *   npx byreal-cli swap execute ... --json | npx tsx playground/sign-and-send.ts
 *
 * Or pass base64 as argument:
 *   npx tsx playground/sign-and-send.ts <base64-transaction>
 *
 * Keypair: place your Solana keypair (byte-array JSON) in playground/keypair.json
 */

import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { Connection, Keypair, VersionedTransaction } from "@solana/web3.js";
import bs58 from "bs58";
import dotenv from "dotenv";

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------

const __dirname = dirname(fileURLToPath(import.meta.url));
dotenv.config({ path: resolve(__dirname, ".env") });

const SECRET_KEY = process.env.SOL_SECRET_KEY;
if (!SECRET_KEY) {
  throw new Error(
    "SOL_SECRET_KEY not set. Copy playground/.env.bak to playground/.env and fill in your base58 secret key.",
  );
}

const RPC_URL = process.env.SOL_ENDPOINT;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function loadKeypair(): Keypair {
  return Keypair.fromSecretKey(bs58.decode(SECRET_KEY!));
}

function readStdin(): Promise<string> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    process.stdin.on("data", (chunk) => chunks.push(chunk));
    process.stdin.on("end", () =>
      resolve(Buffer.concat(chunks).toString("utf-8")),
    );
    process.stdin.on("error", reject);

    // If stdin is a TTY (no pipe), resolve immediately so we fall through to argv
    if (process.stdin.isTTY) resolve("");
  });
}

/**
 * Extract base64 transaction strings from CLI JSON output.
 *
 * Handles two formats:
 *   1. { unsignedTransactions: [base64, ...] }
 *   2. { unsignedTransactions: [{ txPayload: base64, txCode: string }, ...] }
 */
function extractTransactions(json: Record<string, unknown>): string[] {
  const raw = json.unsignedTransactions;
  if (!Array.isArray(raw) || raw.length === 0) {
    throw new Error("No unsignedTransactions found in input JSON");
  }
  return raw.map((item: unknown) => {
    if (typeof item === "string") return item;
    if (item && typeof item === "object" && "txPayload" in item) {
      return (item as { txPayload: string }).txPayload;
    }
    throw new Error(`Unexpected transaction format: ${JSON.stringify(item)}`);
  });
}

async function signAndSend(
  connection: Connection,
  keypair: Keypair,
  base64Tx: string,
  index: number,
  total: number,
): Promise<string> {
  const label = total > 1 ? ` [${index + 1}/${total}]` : "";

  // Deserialize
  const txBuffer = Buffer.from(base64Tx, "base64");
  const transaction = VersionedTransaction.deserialize(txBuffer);
  console.log(
    `${label} Transaction deserialized, signatures: ${transaction.signatures.length}`,
  );

  // Sign
  transaction.sign([keypair]);
  console.log(`${label} Signed`);

  // Send
  console.log(`${label} Sending...`);
  const txid = await connection.sendRawTransaction(transaction.serialize(), {
    skipPreflight: false,
    maxRetries: 3,
  });
  console.log(`${label} Sent — txid: ${txid}`);
  console.log(`${label} https://solscan.io/tx/${txid}`);

  // Confirm
  console.log(`${label} Waiting for confirmation...`);
  const confirmation = await connection.confirmTransaction(txid, "confirmed");
  if (confirmation.value.err) {
    throw new Error(
      `${label} Transaction failed: ${JSON.stringify(confirmation.value.err)}`,
    );
  }
  console.log(`${label} Confirmed!`);
  return txid;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  const keypair = loadKeypair();
  if (!RPC_URL) {
    throw new Error(
      "RPC endpoint not set. Please set SOL_ENDPOINT in playground/.env",
    );
  }
  const connection = new Connection(RPC_URL, "confirmed");

  console.log(`Signer:  ${keypair.publicKey.toBase58()}`);
  console.log(`RPC:     ${RPC_URL}\n`);

  // Determine input source: stdin (pipe) or argv
  let base64Txs: string[];

  const stdinData = (await readStdin()).trim();
  if (stdinData) {
    // Try to parse as JSON first
    try {
      const json = JSON.parse(stdinData);
      base64Txs = extractTransactions(json);
    } catch {
      // Treat as raw base64 string
      base64Txs = [stdinData];
    }
  } else if (process.argv[2]) {
    // Single base64 passed as CLI argument
    base64Txs = [process.argv[2]];
  } else {
    console.error("Usage:");
    console.error(
      "  npx byreal-cli swap execute ... --json | npx tsx playground/sign-and-send.ts",
    );
    console.error("  npx tsx playground/sign-and-send.ts <base64-transaction>");
    process.exit(1);
  }

  console.log(`Transactions to process: ${base64Txs.length}\n`);

  const txids: string[] = [];
  for (let i = 0; i < base64Txs.length; i++) {
    const txid = await signAndSend(
      connection,
      keypair,
      base64Txs[i],
      i,
      base64Txs.length,
    );
    txids.push(txid);
    if (i < base64Txs.length - 1) console.log(""); // separator between txs
  }

  // Final summary
  console.log("\n========================================");
  console.log("All transactions confirmed successfully!");
  console.log("========================================");
  txids.forEach((txid, i) => {
    console.log(`  ${i + 1}. ${txid}`);
  });
}

main().catch((err) => {
  console.error("\nError:", err.message ?? err);
  process.exit(1);
});
